import { type Metadata } from 'next'
import { dark } from '@clerk/themes'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark,
      signIn: { baseTheme: dark },
    }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-[#F8F8F2]`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16 bg-[#282A36]">
            <SignedOut>
              <SignInButton>
                <button className='text-[#F8F8F2] hover:border-2 p-2'>Sign In</button>
              </SignInButton>
              <SignUpButton>
                <button className='text-[#F8F8F2] hover:border-2 p-2'>Sign Up</button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}